import { lazy, Suspense, useEffect, useState } from 'react';
import { ArrowDownRight, ArrowRight, Check, ChevronDown, ExternalLink, Menu, Package, ShieldCheck, X } from 'lucide-react';
const ModelScene = lazy(() => import('./ModelScene').then(m => ({ default: m.ModelScene }))); 
import type { FlowStep, PreparedPayment } from './payFlow';

type Order = { id: string; access: string; status: string; priceLovelace: string; transaction?: string | null };
type Catalog = { product: { priceLovelace: string; maxBatch: number }; paused: boolean; demo?: boolean; pending: number };
const API = (import.meta.env.VITE_API_URL || '').replace(/\/$/, '');
const request = async (path: string, init?: RequestInit) => { const r = await fetch(`${API}${path}`, init); const data = await r.json(); if (!r.ok) throw new Error(data.error || `HTTP ${r.status}`); return data; };
const ada = (v?: string) => (Number(v || 0) / 1_000_000).toFixed(2);
const txUrl = (hash: string) => `https://cardanoscan.io/transaction/${hash}`;
const stored = (): Order | null => { try { return JSON.parse(sessionStorage.getItem('print-order') || 'null'); } catch { return null; } };

export default function App() {
  const [catalog, setCatalog] = useState<Catalog>();
  const [order, setOrder] = useState<Order | null>(stored);
  const [steps, setSteps] = useState<FlowStep[]>([]);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [showAdmin, setShowAdmin] = useState(location.pathname === '/admin');
  const [menu, setMenu] = useState(false);
  const [walletName, setWalletName] = useState('');
  useEffect(() => { request('/api/catalog').then(setCatalog).catch(e => setMessage(e.message)); }, []);
  useEffect(() => { if (!order?.id || !order.access) return; const tick = () => request(`/api/orders/${order.id}`, { headers: { 'x-order-secret': order.access } }).then((o: Order) => { if (o.status !== 'AWAITING_PAYMENT') sessionStorage.removeItem('print-prepared'); setOrder(prev => prev ? { ...prev, ...o } : prev); }).catch(() => {}); tick(); const id = setInterval(tick, 12000); return () => clearInterval(id); }, [order?.id, order?.access]);
  useEffect(() => { if (order) sessionStorage.setItem('print-order', JSON.stringify(order)); }, [order]);
  const saveOrder = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault(); setBusy(true); setMessage('');
    try { const f = new FormData(e.currentTarget); const body = Object.fromEntries(f.entries());
      const created = await request('/api/orders', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...body, productId: 'proof-token', country: 'DE' }) });
      setOrder(created); document.getElementById('checkout')?.scrollIntoView({ behavior: 'smooth' });
    } catch (err) { setMessage(String(err instanceof Error ? err.message : err)); } finally { setBusy(false); }
  };
  const pay = async () => {
    if (!order) return; setBusy(true); setMessage(''); setSteps([]);
    try {
      const [{ createCip30Signer }, { runPaymentFlow }] = await Promise.all([import('./cip30'), import('./payFlow')]);
      const wallets = (window as any).cardano || {}; const choices = Object.entries(wallets).filter(([, w]: any) => typeof w?.enable === 'function');
      if (!choices.length) throw new Error('Install a Cardano CIP-30 wallet, select mainnet, then try again.');
      const [name, wallet] = choices[0] as [string, any]; setWalletName(name); const api = await wallet.enable();
      const signer = await createCip30Signer(api, { baseUrl: 'https://cardano-mainnet.blockfrost.io/api/v0', projectId: import.meta.env.VITE_BLOCKFROST_PROJECT_ID || '' });
      const outcome = await runPaymentFlow(`${API}/api/orders/${order.id}/pay`, signer, step => setSteps(s => [...s, step]), { maxAmount: order.priceLovelace, headers: { 'x-order-secret': order.access }, onPrepared: prepared => sessionStorage.setItem('print-prepared', JSON.stringify(prepared)) });
      if (outcome.status === 'settled') { sessionStorage.removeItem('print-prepared'); setOrder(prev => prev ? { ...prev, status: 'PAID', transaction: (outcome.receipt as any)?.transaction } : prev); }
      else setMessage(`${outcome.message}${'transaction' in outcome && outcome.transaction ? ` Transaction: ${outcome.transaction}` : ''}`);
    } catch (err) { setMessage(String(err instanceof Error ? err.message : err)); } finally { setBusy(false); }
  };
  const retryPayment = async () => {
    setBusy(true); setMessage('');
    try {
      const prepared = JSON.parse(sessionStorage.getItem('print-prepared') || 'null') as PreparedPayment | null;
      if (!prepared || !order || prepared.url !== `${API}/api/orders/${order.id}/pay` || prepared.headers['x-order-secret'] !== order.access) throw new Error('No signed payment for this order. Contact the operator before attempting another payment.');
      const { resumePaymentFlow } = await import('./payFlow');
      const outcome = await resumePaymentFlow(prepared, step => setSteps(s => [...s, step]));
      if (outcome.status === 'settled') { sessionStorage.removeItem('print-prepared'); setOrder(prev => prev ? { ...prev, status: 'PAID', transaction: (outcome.receipt as any)?.transaction } : prev); }
      else setMessage(outcome.message);
    } catch (e) { setMessage(String(e)); } finally { setBusy(false); }
  };
  const demoPay = async () => {
    if (!order) return; setBusy(true); setMessage(''); setSteps([]);
    try {
      const url = `/api/orders/${order.id}/pay`, headers = { 'x-order-secret': order.access };
      const offer = await fetch(`${API}${url}`, { method: 'POST', headers });
      if (offer.status !== 402) throw new Error(`Expected HTTP 402, got ${offer.status}`);
      setSteps([{ id: 'request', title: 'POST /pay → HTTP 402' }, { id: 'offer', title: 'Local simulation offer', detail: await offer.json() }, { id: 'signed', title: 'Local demo payment (no wallet or ADA)', detail: { nonce: 'local-demo' } }]);
      const paid = await request(url, { method: 'POST', headers: { ...headers, 'x-demo-payment': 'local-demo' } });
      setSteps(s => [...s, { id: 'settled', title: 'HTTP 200 — simulated settlement', detail: paid }]);
      setOrder(prev => prev ? { ...prev, status: 'PAID' } : prev);
    } catch (e) { setMessage(String(e)); } finally { setBusy(false); }
  };
  const reset = () => { if (sessionStorage.getItem('print-prepared')) { setMessage('A signed payment is still unresolved. Recheck it or contact the operator before starting another order.'); return; } sessionStorage.removeItem('print-order'); sessionStorage.removeItem('print-prepared'); setOrder(null); setSteps([]); setMessage(''); };
  return <div className="app">
    <header className="nav shell"><a href="/" className="brand"><span className="brand-mark">4<span>0</span>2</span><span className="brand-divider"/>PRINT<br/>PROTOCOL</a><nav className={menu ? 'open' : ''}><a href="#object" onClick={() => setMenu(false)}>The object</a><a href="#protocol" onClick={() => setMenu(false)}>How it works</a><a href="#checkout" onClick={() => setMenu(false)}>Get yours</a><a href="/admin" onClick={e => { e.preventDefault(); history.pushState({}, '', '/admin'); setShowAdmin(true); setMenu(false); }}>Operator ↗</a></nav><button className="mobile-menu" onClick={() => setMenu(v => !v)} aria-label="Open navigation">{menu ? <X/> : <Menu/>}</button><a href="#checkout" className="nav-cta">ORDER A PRINT <ArrowRight size={15}/></a></header>
    {showAdmin ? <Admin onClose={() => { history.pushState({}, '', '/'); setShowAdmin(false); }} /> : <>
      <main>
        <section className="hero shell"><div className="hero-top"><span className="eyebrow"><span className="pulse"/> {catalog?.demo ? 'LOCAL SIMULATION · NO ADA' : 'LIVE EXPERIMENT · CARDANO MAINNET'}</span><span className="serial">EDITION 001 / THE INTERNET OF THINGS</span></div><div className="hero-grid"><div className="hero-copy"><div className="orange-spark">✳</div><h1>A payment.<br/>A print.<br/><em>A little magic.</em></h1><p>Send ADA over the internet. Watch an actual 3D printer turn a digital handshake into something you can hold.</p><a href="#checkout" className="primary">MAKE IT REAL <ArrowDownRight size={22}/></a><div className="hero-foot"><span>01 / ONE PHYSICAL OBJECT</span><span>02 / ONE ON-CHAIN PAYMENT</span></div></div><Suspense fallback={<div className="scene-wrap scene-loading">Preparing the 3D study…</div>}><ModelScene/></Suspense></div><div className="hero-bottom"><span>THE EXPERIMENT <span className="small-arrow">↘</span></span><span>SCROLL TO DISCOVER</span></div></section>
        <section id="object" className="object-section"><div className="shell object-grid"><div className="section-index"><span>01 — THE OBJECT</span><span className="index-line"/></div><div><h2>Meet the <em>Proof of Print.</em></h2><p className="lead">A pocket sized physical receipt for an internet native transaction. Designed for this experiment, made layer by layer on a Snapmaker U1.</p><div className="spec-grid"><div><span>01 / FORMAT</span><strong>Ø 54 mm</strong><small>Desk friendly token</small></div><div><span>02 / MATERIAL</span><strong>PLA</strong><small>Color varies by run</small></div><div><span>03 / PROCESS</span><strong>FDM</strong><small>Made on demand</small></div></div><a href="#checkout" className="text-link">Own the experiment <ArrowRight size={18}/></a></div></div></section>
        <section id="protocol" className="protocol-section shell"><div className="section-index"><span>02 — THE PROTOCOL</span><span className="index-line"/></div><div className="protocol-intro"><h2>The internet says <span>pay me.</span><br/>Your printer says <em>okay.</em></h2><p>HTTP 402 is the web’s “payment required” status. x402 gives it a working payment conversation. Here, the payment is a real Cardano mainnet transaction.</p></div><div className="protocol-steps"><div><span className="step-num">01</span><span className="http-pill">POST /pay</span><h3>Ask for the print</h3><p>Your browser requests the protected print order.</p></div><div><span className="step-num">02</span><span className="http-pill hot">HTTP 402</span><h3>Get the price</h3><p>The API returns the exact ADA amount, address and mainnet payment rules.</p></div><div><span className="step-num">03</span><span className="http-pill">PAYMENT-SIGNATURE</span><h3>Sign in your wallet</h3><p>Your wallet signs a transaction. The hosted facilitator verifies and settles it.</p></div><div><span className="step-num">04</span><span className="http-pill green">HTTP 200</span><h3>Make it tangible</h3><p>Paid orders queue for a supervised print batch and delivery.</p></div></div><div className="protocol-note"><span>↗</span><p>The live checkout below exposes each HTTP step and its payment receipt so you can see the protocol in action.</p></div></section>
        <section id="checkout" className="checkout-section"><div className="shell"><div className="checkout-head"><div><span className="eyebrow">03 — FROM DIGITAL TO PHYSICAL</span><h2>Your move<span className="period">.</span></h2></div><p>One small object. One real mainnet transaction. A story you can put on your desk.</p></div><div className="checkout-grid"><div className="order-panel"><div className="panel-top"><span>YOUR ORDER / 001</span><span>● {catalog?.paused ? 'PAUSED' : 'AVAILABLE'}</span></div><div className="product-row"><div className="product-symbol">✳</div><div><strong>Proof of Print</strong><small>3D printed token · quantity 1</small></div><b>₳ {ada(catalog?.product.priceLovelace)}</b></div><div className="divider"/><div className="price-row"><span>Print + handling</span><strong>₳ {ada(catalog?.product.priceLovelace)}</strong></div><p className="fineprint">Delivery currently available within Germany. We’ll use your address solely to fulfill this order. Shipping is included in this demo price.</p>
          {!order ? <form onSubmit={saveOrder} className="order-form"><label>Your name<input name="name" required maxLength={100} placeholder="Ada Lovelace"/></label><label>Email for order questions<input type="email" name="email" required maxLength={160} placeholder="ada@example.com"/></label><label>Street and house number<input name="addressLine1" required maxLength={180} placeholder="Example Street 42"/></label><label>Address addition <small>optional</small><input name="addressLine2" maxLength={180} placeholder="Apartment, c/o"/></label><div className="form-pair"><label>Postal code<input name="postalCode" required pattern="[0-9]{5}" placeholder="10115"/></label><label>City<input name="city" required maxLength={100} placeholder="Berlin"/></label></div><button className="primary form-submit" disabled={busy || catalog?.paused}>{busy ? 'PREPARING…' : 'CONTINUE TO PAYMENT'} <ArrowRight size={18}/></button><p className="form-disclaimer">By continuing, you agree to the delivery and refund notes below. No wallet access is requested until you choose to pay.</p></form> : <div className="order-state"><div className="state-header"><Check size={18}/> ORDER {order.id.slice(0, 8).toUpperCase()}</div><p>Status: <strong>{order.status.replaceAll('_', ' ')}</strong></p>{order.transaction && <a className="text-link" target="_blank" rel="noreferrer" href={txUrl(order.transaction)}>View mainnet transaction <ExternalLink size={15}/></a>}{order.status === 'AWAITING_PAYMENT' && <button className="primary form-submit" disabled={busy} onClick={catalog?.demo ? demoPay : sessionStorage.getItem('print-prepared') ? retryPayment : pay}>{busy ? 'PROCESSING…' : catalog?.demo ? 'SIMULATE HTTP 402 PAYMENT' : sessionStorage.getItem('print-prepared') ? 'RECHECK SIGNED PAYMENT' : 'CONNECT WALLET & PAY'} <ArrowRight size={18}/></button>}<button className="subtle" onClick={reset}>Start another order</button></div>}
          {message && <div className="error-message" role="alert">{message}</div>}
        </div><div className="trace-panel"><div className="panel-top"><span>LIVE PROTOCOL TRACE</span><span className="live-indicator">● LIVE</span></div><div className="terminal"><div className="terminal-title"><span className="terminal-dots">● ● ●</span> payment.session <span>{catalog?.demo ? 'LOCAL DEMO' : 'MAINNET'}</span></div>{steps.length ? steps.map((s, i) => <div className="trace-step" key={`${s.id}-${i}`}><span className="trace-index">{String(i + 1).padStart(2, '0')}</span><div><strong>{s.title}</strong>{'detail' in s && <pre>{JSON.stringify(s.detail, null, 2)}</pre>}</div></div>) : <div className="terminal-empty"><span className="cursor">▌</span><p>Your live HTTP conversation will appear here when you pay.</p></div>}</div><div className="trace-foot"><ShieldCheck size={18}/> {catalog?.demo ? 'Local payment simulation: no blockchain transaction occurs.' : 'The server never sees your wallet keys. Your delivery address is visible only to the operator.'}</div></div></div></div></section>
        <section className="faq shell"><div><span className="eyebrow">A FEW GOOD QUESTIONS</span><h2>Small print.<br/><em>Big idea.</em></h2></div><div className="faq-list"><details><summary>Is this a real purchase? <ChevronDown size={18}/></summary><p>Yes. This is Cardano mainnet. Confirm the ADA amount in your wallet before signing. The printed object is physical and will be sent to the address you provide.</p></details><details><summary>When will my print ship? <ChevronDown size={18}/></summary><p>Prints are grouped into small supervised batches of up to four. This is a small experiment, so timing can vary. We will contact you by email if there is a problem.</p></details><details><summary>What if printing fails? <ChevronDown size={18}/></summary><p>The operator reviews failed jobs and can arrange a reprint or a manual refund. On-chain payments are not automatically reversible. Contact the operator using the address published in the repository.</p></details><details><summary>What happens to my address? <ChevronDown size={18}/></summary><p>Your delivery details are stored in the order database for fulfillment. They are never placed on chain or sent to the printer. The public source code contains no customer data.</p></details></div></section>
      </main><footer><div className="shell footer-grid"><div className="footer-brand">402<span>✳</span></div><div><span>AN OPEN EXPERIMENT</span><p>Making internet native payments tangible, one layer at a time.</p></div><div><span>FOLLOW THE BUILD</span><a href="https://github.com/Kammerlo/x402-cardano-3dprinting-service" target="_blank" rel="noreferrer">SOURCE ON GITHUB ↗</a></div><div className="footer-end">CARDANO MAINNET · 2026</div></div></footer>
    </>}
  </div>;
}

function Admin({ onClose }: { onClose: () => void }) {
  const [token, setToken] = useState(sessionStorage.getItem('print-admin') || ''); const [data, setData] = useState<any>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = async (secret = token) => { try { setError(''); const d = await request('/api/admin/orders', { headers: { authorization: `Bearer ${secret}` } }); setData(d); sessionStorage.setItem('print-admin', secret); } catch (e) { setError(String(e)); } };
  useEffect(() => { if (token) void load(token); const t = setInterval(() => { if (token) void load(token); }, 15000); return () => clearInterval(t); }, []);
  const action = async (path: string, body?: object) => { setBusy(true); try { await request(path, { method: 'POST', headers: { authorization: `Bearer ${token}`, 'content-type': 'application/json' }, body: JSON.stringify(body || {}) }); await load(); } catch (e) { setError(String(e)); } finally { setBusy(false); } };
  return <main className="admin shell"><div className="admin-heading"><div><span className="eyebrow">OPERATOR SPACE / PRIVATE</span><h1>Print desk<span className="period">.</span></h1></div><button className="text-link" onClick={onClose}>Back to storefront <ArrowRight size={18}/></button></div><form className="admin-login" onSubmit={e => { e.preventDefault(); void load(); }}><label>Operator token<input type="password" value={token} onChange={e => setToken(e.target.value)} placeholder="Enter admin token"/></label><button className="primary">UNLOCK DASHBOARD <ArrowRight size={18}/></button></form>{error && <div className="error-message">{error}</div>}{data && <><div className="admin-stats"><div><span>ALL ORDERS</span><strong>{data.orders.length}</strong></div><div><span>PAID / WAITING</span><strong>{data.orders.filter((o: any) => o.status === 'PAID').length}</strong></div><div><span>ON THE PRINTER</span><strong>{data.orders.filter((o: any) => o.status === 'PRINTING').length}</strong></div><div><span>READY TO SHIP</span><strong>{data.orders.filter((o: any) => o.status === 'PRINTED').length}</strong></div></div><div className="admin-actions"><button disabled={busy} onClick={() => action('/api/admin/batches')}>Create batch (up to 4) ↗</button><button disabled={busy} onClick={() => action('/api/admin/pause', { paused: !data.paused })}>{data.paused ? 'Resume orders' : 'Pause new orders'}</button><button onClick={() => load()}>Refresh</button></div><h2>Orders</h2><div className="table-wrap"><table><thead><tr><th>ORDER</th><th>CUSTOMER & DELIVERY</th><th>STATUS</th><th>BATCH</th><th>TX</th><th>ACTION</th></tr></thead><tbody>{data.orders.map((o: any) => <tr key={o.id}><td><code>{o.id.slice(0, 8)}</code><small>{new Date(o.created_at).toLocaleString()}</small></td><td><strong>{o.customer_name}</strong><small>{o.email}<br/>{o.address_line1} {o.address_line2}<br/>{o.postal_code} {o.city}, {o.country}</small></td><td><span className={`status status-${o.status.toLowerCase()}`}>{o.status}</span></td><td><code>{o.batch_id?.slice(0, 8) || '—'}</code><small>{o.batch_status || ''}</small></td><td>{o.tx_hash ? <a href={txUrl(o.tx_hash)} target="_blank" rel="noreferrer">Explorer ↗</a> : '—'}</td><td>{['PRINTED', 'NEEDS_REVIEW'].includes(o.status) && <><button disabled={busy} onClick={() => action(`/api/admin/orders/${o.id}/status`, { status: 'SHIPPED' })}>Mark shipped</button><button disabled={busy} onClick={() => action(`/api/admin/orders/${o.id}/status`, { status: 'REFUNDED' })}>Mark refunded*</button></>}</td></tr>)}</tbody></table></div><p className="fineprint">*Status labels record operator action only. A refund requires a separate wallet transfer and manual reconciliation.</p><h2>Print batches</h2><div className="batch-list">{data.batches.map((b: any) => <div key={b.id}><Package size={21}/><strong>{b.id.slice(0, 8)}</strong><span>{b.size} objects</span><span>{b.status}</span><small>{b.printer_filename || 'Awaiting gateway'}</small></div>)}</div></>}</main>;
}
